name: bloc_code_generator
description: Bloc Code Generator is a code generator for https://github.com/felangel/bloc package.
version: 1.0.0
author: mutang <124561376@qq.com>
homepage: https://github.com/adsonpleal/bloc-code-generator


environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  build: ^1.0.0
  analyzer: ^0.39.4
  source_gen: ^0.9.4+7
